version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/user
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 15
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 15
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 15
      runas: root